### ISSUE TITLE
Using this sink with NodaTime in .Net Core 2.2

### ISSUE THREAD

**Issue by thecodemonk** [SeppPenner/SerilogSinkForPostgreSQL#10]
This is definitely not a bug with this sink, but more of a problem with plugins for Npgsql. However, I would like to know if there is something I can do. The NodaTime plugin registers globally and registers type handlers for the NodaTime types, making it near impossible to use the BCL types in favor of the NodaTime types. So, currently, when Serilog tries to write to the table in postgres, I'm getting the exception: "Can't write CLR type System.DateTimeOffset with handler type TimestampTzHandler". 

Now, I know it's a NodaTime issue because if I run with the global initializer off, it works, however as soon as EF Core is initialized with the NodaTime plugin, it stops working, because the plugin is global. 

There are talks of them making changes to support this better, but right now I'm stuck. Any suggestions on what I can do to get around this?

**Comment by SeppPenner** [comment]
I guess, this is the bug (or a similar one) I already mentioned in https://github.com/npgsql/npgsql/issues/2470.

However, this `"Can't write CLR type System.DateTimeOffset with handler type TimestampTzHandler"` shouldn't happen... My bug was about a failure in the documentation of NPGSQL where mapping a `DateTimeOffset` to a `Timestamp` didn't work, but not mapping a `DateTimeOffset` to a `TimestampTz`.

Do you have a minimal reproduceable example for me? It would be easier to check this and see what I can do or if it's really a bug in NodaTime I can't handle here.

**Comment by thecodemonk** [comment]
Thanks for the quick response. I created a small sample project. Initial commit is everything set up, except NodaTime and verified working. I then added NodaTime to the project and the EF Core DbContext and I start seeing the above error message.

[Sample](https://github.com/thecodemonk/SerilogPostgresNodaTime)

**Comment by thecodemonk** [comment]
I think I have a solution (for me, at least). I just created a new column writer for that field. I don't know why I didn't think of this last night, but I guess I wasn't thinking. 

`    public class OffsetDateTimeColumnWriterBase : ColumnWriterBase
    {
        public OffsetDateTimeColumnWriterBase(NpgsqlDbType dbType = NpgsqlDbType.TimestampTz): base(dbType)
        {
            this.DbType = NpgsqlDbType.TimestampTz;
        }

        public override object GetValue(LogEvent logEvent, IFormatProvider formatProvider = null)
        {
            return OffsetDateTime.FromDateTimeOffset(logEvent.Timestamp);
        }
    }`

**Comment by SeppPenner** [comment]
This is indeed strange... So, the issue is the `GetValue` function returning `logEvent.Timestamp;`.

Check https://github.com/SeppPenner/SerilogSinkForPostgreSQL/blob/2b438dbb38aa8afd3b42068dde9e9f4281b12c11/SerilogSinksPostgreSQL/SerilogSinksPostgreSQL/Sinks/PostgreSQL/TimestampColumnWriter.cs#L51.

To be honest, I don't know why this is a problem with NodaTime...

**Comment by SeppPenner** [comment]
I have documented this here: https://github.com/SeppPenner/SerilogSinkForPostgreSQL#using-the-sink-with-nodatime-in-net-core-22.

I don't think there is anything else I can do?
