### ISSUE TITLE
 .ReadFrom.Configuration doesn't call the LoggerSinkConfiguration  extension

### ISSUE THREAD

**Issue by artiomponkratov** [SeppPenner/SerilogSinkForPostgreSQL#11]
Hi,
I need to add the configuration for PostgreSQL from JSON file.
First, I took a look how it works for MSSQL
The is a code for creating logger from configuration

   ```
   var serilogLogger = new LoggerConfiguration()
                .ReadFrom.Configuration(configuration)
                .CreateLogger();
```
				
it looks for extensions on `LoggerSinkConfiguration ` and runs the best suitable.

I tried to do the same with PostgreSQL.

[I created a sample project](https://gofile.io/d/Dndocz)

If I have a reference to `Serilog.Sinks.PostgreSQL` that was created by @b00ted  and forked to this repo, I got the expected error 'Cannot create instance of type 'Serilog.Sinks.PostgreSQL.ColumnWriterBase' because it is either abstract or an interface.'
Other words, it sees the extension.

But when I change the reference to your package, I got nothing. It doesn't touch the extension method at
[LoggerConfigurationPostgreSQLExtensions](https://github.com/SeppPenner/SerilogSinkForPostgreSQL/blob/master/src/SerilogSinksPostgreSQL/LoggerConfigurationPostgreSQLExtensions.cs)

I can't figure out, why it doesn't see the extension. 
Could you help with this ?

**Comment by artiomponkratov** [comment]
I found the root of the issue.
It is about case sensitive method names.
In my sample JSON,  I have the sink with attribute

` "Name": "PostgreSQL",`

And it looks for the method with **all-capital SQL** as it in the name.
The difference of the LoggerConfigurationPostgreSQLExtensions classes between your's and @b00ted  is the name of the extension method)

I changed the config to have ` "Name": "PostgreSql",` and it works!

**Comment by SeppPenner** [comment]
When I thaught about this yesterday, I already was sure that this might be the issue... I will document this soon in the readme to avoid this error in the future :)

**Comment by SeppPenner** [comment]
Just one more question: Your configuration looks somehow like this I guess?

```json
{
    "Serilog": {
        "Using": [ "Serilog.Sinks.PostgreSql" ],
        "MinimumLevel": {
            "Default": "Warning"
        },
        "WriteTo": [
            {
                "Name": "PostgreSql",
                "Args": {
                    "connectionString": "User ID=serilog;Password=serilog;Host=localhost;Port=5432;Database=Logs",
                    "tableName": "logs"
                }
            }
        ]
    }
}
```

**Comment by artiomponkratov** [comment]
Yes, with this config it will create the table with standard columns.
But I need to customize the columns - I will create a PR to your repo soon)

**Comment by SeppPenner** [comment]
This is documented under https://github.com/SeppPenner/SerilogSinkForPostgreSQL/blob/master/HowToUse.md#configuration-via-json-options now.

> But I need to customize the columns - I will create a PR to your repo soon)

Ok, that's a different thing 😄 Yes, please. You can add one and I will check it :)

**Comment by SeppPenner** [comment]
I have seen you pull request. I will take a look at it soon :)
