### ISSUE TITLE
Exception column is getting the wrong data 

### ISSUE THREAD

**Issue by GZidar** [SeppPenner/SerilogSinkForPostgreSQL#15]
Line 160 in the file LoggerConfigurationPostgreSQLExtensions.cs is initialising the Exception case with the RenderedMessageColumnWriter instead of the ExceptionColumnWriter

**Comment by SeppPenner** [comment]
I have merged the pull request and will release a new version soon. Don't hesitate to create a new issue if you find anything else.

**Comment by SeppPenner** [comment]
Version 2.2.0 is out soon.
