### ISSUE TITLE
Option to add level as text for configuration with json file

### ISSUE THREAD

**Issue by OlgaLevchenkoEmpeek** [SeppPenner/SerilogSinkForPostgreSQL#17]
Hi!

Could you please add an option of storing log event level as text when configuring logger via json or provide any workarounds?

As far as I can see [here](https://github.com/SeppPenner/SerilogSinkForPostgreSQL/blob/78646c52a59f58d8a2c9bc1b57caeb8f9a6aa063/src/SerilogSinksPostgreSQL/LoggerConfigurationPostgreSQLExtensions.cs#L142), currently level can be stored in the database only as int if it is configured via json file.

I will appreciate any response.

Olga.

**Comment by SeppPenner** [comment]
I can try to add a new option to change this behaviour. I'm not sure if I should really do this, however.

I'm not a fan of reoccuring texts in the database if they can be handled by an enum. In my opinion, changes to this behaviour would violate the 2NF of SQL databases (Check e.g. https://www.edureka.co/blog/normalization-in-sql/).

There are two options now:
* You can create a table to store the enum values as key value tables by your own. Something like this:

```sql
CREATE TABLE loglevel
( 
    Id INT NOT NULL,
    Description TEXT NOT NULL
);

INSERT INTO loglevel (Id, Description) VALUES (0, 'Verbose');
INSERT INTO loglevel (Id, Description) VALUES (1, 'Debug');
INSERT INTO loglevel (Id, Description) VALUES (2, 'Information');
INSERT INTO loglevel (Id, Description) VALUES (3, 'Warning');
INSERT INTO loglevel (Id, Description) VALUES (4, 'Error');
INSERT INTO loglevel (Id, Description) VALUES (5, 'Fatal');
```

When you query, you do so by e.g. querying:

```sql
SELECT * FROM logs INNER JOIN loglevel ON logs.Level = loglevel.Id WHERE ...
```

* I can integrate the option to store the texts in the database but it might take some time.

**Comment by OlgaLevchenkoEmpeek** [comment]
Thanks for your reply!

**Comment by SeppPenner** [comment]
This will be added automatically in version 2.4.0 (The `LogLevel` table). I might add the feature to store the log levels really as texts as well, but I'm still not sure if I should.

**Comment by OlgaLevchenkoEmpeek** [comment]
My underlying idea is that: as far as this option is available via code configuration, probably it is a good idea to have the same option for json configuration, which will provide the same agility for it. At the moment I don't have a need in the described behaviour, though I was considering it.
Thank you for your response! I am grateful for your taking care of the users needs.

**Comment by SeppPenner** [comment]
Yes, that makes sense. I was about to already add this, but I'm still busy at the moment. Let's see when I get the time to add this.

**Comment by shouaib-ahmed** [comment]
I was looking at the latest release and the changes. It seems that log level table will always be created. I think it should be optional as not all user will want to do that. In some cases the database account might not even have permissions to create tables. Can you please make this optional?

**Comment by SeppPenner** [comment]
@shouaib-ahmed You're right. I will need to change the configuration therefore as well.

**Comment by SeppPenner** [comment]
And I should probably add some tests to read the json settings to avoid such things in the future...

**Comment by SeppPenner** [comment]
This should be possible now with version 2.5.0 and the column property `LevelAsText`. I have created a test that creates the table successfully :)

@shouaib-ahmed: I have removed the log event level lookup table completely again as I don't think it's really neccessary.
