### ISSUE TITLE
.Net CORE 3.1 Web API do not save data

### ISSUE THREAD

**Issue by rpimentaf** [SeppPenner/SerilogSinkForPostgreSQL#19]
I developed a WEB API using .Net Core 3.1 with Serilog. If the sink is file, the application produces a log file without problem.
In another hand, if the sink is PostgreSQL, the application reads appsettings.json, creates the table in the SGBD, but nothing is saved.

In addition, what is it for the field "loggerPropertyColumnOptions" in the appsettings.json that is showed in "Basic Usage" page.

Tks in advance!!!

[appsettings.json.txt](https://github.com/SeppPenner/SerilogSinkForPostgreSQL/files/5568912/appsettings.json.txt)

**Comment by SeppPenner** [comment]
I will check this and reply to you. By the way, if there are your real passwords in the appsettings file, you should remove them...

**Comment by SeppPenner** [comment]
I guess, you are missing `loggerColumnOptions`. There, you can define how the data is written to the database. `loggerColumnOptions` contains the standard data fields as shown under https://github.com/SeppPenner/SerilogSinkForPostgreSQL/blob/master/HowToUse.md#configuration-via-json-file.

`loggerPropertyColumnOptions` is a configuration for you to add additional custom properties and how they should be written to the database. I hope, I could help you with that.
