### ISSUE TITLE
document : how can set config in appsetting json 

### ISSUE THREAD

**Issue by behroozbc** [SeppPenner/SerilogSinkForPostgreSQL#20]
hi 
how can i set config in appsetting json ??

**Comment by SeppPenner** [comment]
I will check this out and update the readme :)

**Comment by SeppPenner** [comment]
Hi, there is an example already under https://github.com/SeppPenner/SerilogSinkForPostgreSQL/blob/master/src/SerilogSinksPostgreSQL.IntegrationTests/JsonConfigTest.cs and https://github.com/SeppPenner/SerilogSinkForPostgreSQL/blob/master/src/SerilogSinksPostgreSQL.IntegrationTests/PostgreSinkConfiguration.json. I will add this to the readme as well.

**Comment by SeppPenner** [comment]
By the way, there is an example in the readme already: https://github.com/SeppPenner/SerilogSinkForPostgreSQL/blob/master/HowToUse.md#configuration-via-json-file. And you might want to look at https://github.com/serilog/serilog-settings-configuration, where this is explained in detail. Hope, this helps you.
