### ISSUE TITLE
PostgreSQL vs PostgreSql

### ISSUE THREAD

**Issue by ps30** [SeppPenner/SerilogSinkForPostgreSQL#22]
Just a tiny note it looks you made a change with .WriteTo.PostgreSQL to .WriteTo.PostgreSql (SQL vs Sql) and this shows an error when using your updated package vs the original.  Not a show-stopper, but maybe make a note in the updated docs to reflect this change.  This article also brought it home as a funny: [the-shibboleth-of-postgresql](https://www.cybertec-postgresql.com/en/the-shibboleth-of-postgresql/).  Great work and thank you for keeping this important project fresh.

![SQLtoSql-Screenshot 2020-12-30 083538](https://user-images.githubusercontent.com/12287002/103477191-b938e180-4dee-11eb-91ed-973f791c44cc.png)

**Comment by SeppPenner** [comment]
Hi, thank you for the information. I totally forgot about that change... I will add this to the readme soon.

Yeah, this was a refactoring due to my Resharper language style settings, I understand the issue though :D

**Comment by SeppPenner** [comment]
In the new version of the sink, I have added both versions (The one with `SQL` just as override of the others). Maybe, I will go back to the original version in a later revision and mark the other as deprecated, we will see. There's a new information on this in the readme from now on: https://github.com/SeppPenner/SerilogSinkForPostgreSQL/blob/master/README.md#further-information
