### ISSUE TITLE
Add support for named connection strings

### ISSUE THREAD

**Issue by cygnim** [SeppPenner/SerilogSinkForPostgreSQL#24]
Similar to this [ticket](https://github.com/serilog/serilog-sinks-mssqlserver/issues/150) MS SQL Server.  It is standard practice to store connection strings in the connectionStrings section of config. This also facilitates storing sensitive data (like db passwords) in the key vault, separate from other configuration information.

Ideally, it would be great if this sink supported the following configuration scenario:
```
{
  "ConnectionStrings": {
    "DevTest": "Host=localhost; Port=5432; Database=dbName..."
  },
  "Serilog": {
    "WriteTo": [
      {
        "Name": "PostgreSql",
        "Args": {
          "connectionString": "DevTest"
        }
      }
    ]
  }
}
```

**Comment by SeppPenner** [comment]
Ok, I will check how this is implemented in the other project and see if I can add this in a similar way soon.

**Comment by SeppPenner** [comment]
Just for reference, the sink will only allow `Microsoft.Extensions` as `System.Configuration`'s `ConfigurationManager` is not available on all targets (including the newer frameworks):

![grafik](https://user-images.githubusercontent.com/9639361/106364214-af42c980-632d-11eb-858f-66921056c7c1.png)

It's only available in NetFramework and I don't want to maintain legacy stuff here :D

**Comment by SeppPenner** [comment]
Ok, I need to dig a bit deeper on this as I don't really understand how they did it in MSSQLServer yet.

**Comment by SeppPenner** [comment]
This should work now with version 3.3.0: https://github.com/SeppPenner/SerilogSinkForPostgreSQL/blob/master/HowToUse.md#configuration-via-json-file-to-use-named-connection-strings.
