### ISSUE TITLE
This nuget requires adding the CREATE privilege on schema level

### ISSUE THREAD

**Issue by Mikilll94** [SeppPenner/SerilogSinkForPostgreSQL#26]
I wanted to prepare my database for production. I have noticed that If you will not add the CREATE privilege on schema level, the logging will just not work. Of course I am assuming that the user which is connecting to the database is not a superuser.

Additionally this nugget does not produce any logs or debug info. I had to spend hours on debugging to figure out what is going on.

**Comment by SeppPenner** [comment]
> I have noticed that If you will not add the CREATE privilege on schema level, the logging will just not work. Of course I am assuming that the user which is connecting to the database is not a superuser.

Which options did you set in the configuration? Normally, this can be solved by adding the database before the setup and setting the options `needAutoCreateTable` and `needAutoCreateSchema` to `false`.

> Additionally this nugget does not produce any logs or debug info. I had to spend hours on debugging to figure out what is going on.

You should be able to get log message by using the `failureCallback`.

Check https://github.com/SeppPenner/SerilogSinkForPostgreSQL/blob/master/HowToUse.md, please.

**Comment by Mikilll94** [comment]
@SeppPenner 
Thanks. I was using an older version and I didn't know about `needAutoCreateSchema` and `failureCallback`. Now everything is working fine.

**Comment by SeppPenner** [comment]
Ok, great. The features were added recently (Especially `needAutoCreateSchema`) after someone complained about the same thing as you did :) Glad to hear that it works, I already thought that there is an issue with that mechanism.
