### ISSUE TITLE
"queueLimit" param doesn't exist

### ISSUE THREAD

**Issue by jliglesias-fidesol** [SeppPenner/SerilogSinkForPostgreSQL#30]
Helo!

I have not found the "queueLimit" as parameter when I instantiate the PostgreSQL() method.

I have reviewed the code, but there isn't there neither.

Will you add this parameter in the future, did you forget to implemented or have you removed it by any reason?

Regards!

**Comment by SeppPenner** [comment]
Either the parameter was renamed and I forgot to update the documentation or I missed it. I will check this now :)

**Comment by SeppPenner** [comment]
You're right, I missed the parameters for `QueueLimit` and `EagerlyEmitFirstEvent`. Will be available in the next version of the sink.

**Comment by SeppPenner** [comment]
Version 3.3.7 contains the update and should be available soon :)
